name: Auto Build & Release

on:
  push:
    branches: [ main ]

jobs:
  build-and-release-windows:
    name: Build Windows and publish
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build renderer (Vite)
        run: npm run build

      - name: Build Windows installer (electron-builder)
        run: npm run dist:win

      - name: Create GitHub Release and upload artifacts
        uses: ncipollo/release-action@v1
        with:
          tag: auto-${{ github.run_id }}
          name: Auto release ${{ github.run_number }}
          files: release/**
          body: "Automated build from commit ${{ github.sha }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
